name: CI/CD

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run frontend unit tests
        run: npm run unit

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token $VERCEL_TOKEN --prod

      # Create preview deployments for pull requests
      - name: Create Vercel Preview Deployment
        if: github.event_name == 'pull_request'
        run: |
          npm install -g vercel
          vercel --token $VERCEL_TOKEN --edge
