name: CI/CD

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run frontend unit tests
        run: npm run unit